[package]
name = "jj-commit-cloud-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "jj-cc-server"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.39", features = ["rt-multi-thread", "macros", "net", "signal"] }
clap = { version = "4", features = ["derive"] }
tonic = "0.12"
tonic-health = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
