[package]
name = "jj-commit-cloud-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "jj-cc-server"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.39", features = ["rt-multi-thread", "macros", "net", "signal", "process"] }
clap = { version = "4", features = ["derive"] }
tonic = "0.12"
tonic-health = "0.12"
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
cc-proto = { path = "../proto" }
uuid = { version = "1", features = ["v4"] }
blake3 = "1.5"
hex = "0.4"
sled = "0.34"
rusqlite = { version = "0.31", features = ["bundled"] }
prost = "0.13"


[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
testutils = { path = "../testutils" }
