[package]
name = "cc-lib"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
jj-lib = "0.43.0"
async-trait = "0.1"
futures = "0.3"
uuid = { version = "1", features = ["v4"] }
cc-proto = { path = "../proto" }
tonic = { version = "0.12", features = ["tls", "tls-webpki-roots"] }

tokio = { version = "1.39", features = ["rt-multi-thread", "macros"] }
blake3 = "1.5"
gix = "0.85"

